AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation SES Providers

Parameters:
  LambdaCodeS3Bucket:
    Type: String
    Default: the-daly-nugget-custom-cfn-resources
  LambdaCodeS3Key:
    Type: String
    Default: Briex/cfn-ses-provider-0.6.4.zip

Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNSESProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-ses-provider'
          - Effect: Allow
            Action:
              - route53:GetHostedZone
              - route53:ChangeResourceRecordSets
              - route53:ListResourceRecordSets
            Resource: '*'
          - Effect: Allow
            Action:
              - ses:VerifyDomainDkim
              - ses:DeleteIdentity
              - ses:ListIdentities
              - ses:VerifyDomainIdentity
              - ses:DescribeActiveReceiptRuleSet
              - ses:SetActiveReceiptRuleSet
              - ses:GetIdentityVerificationAttributes
              - ses:GetIdentityNotificationAttributes
              - ses:SetIdentityNotificationTopic
              - ses:SetIdentityHeadersInNotificationsEnabled
              - ses:SetIdentityFeedbackForwardingEnabled
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNSESProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
      - LambdaPolicy
    Properties:
      Description: CloudFormation SES provider implementation
      Code:
        S3Bucket:   !Ref 'LambdaCodeS3Bucket'
        S3Key:      !Ref 'LambdaCodeS3Key'
      FunctionName: binxio-cfn-ses-provider
      Handler: ses.handler
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.6
      Timeout: 30
